"""colemn to json

Revision ID: 2567b0f68db0
Revises: 3a578b6b3355
Create Date: 2026-03-10 15:20:17.221590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2567b0f68db0'
down_revision: Union[str, Sequence[str], None] = '3a578b6b3355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('live_matches', 'PredictRadiant',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('live_matches', 'PredictRadiant',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
