"""add PredictRadiant to live_matches

Revision ID: 29200001625a
Revises: 6e38419b4f6c
Create Date: 2026-01-18 15:41:16.514422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29200001625a'
down_revision: Union[str, Sequence[str], None] = '6e38419b4f6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshot_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.BigInteger(), nullable=True),
    sa.Column('full_match_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predict_radiant', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('live_matches', sa.Column('PredictRadiant', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_matches', 'PredictRadiant')
    op.drop_table('snapshot_matches')
    # ### end Alembic commands ###
