"""update  model Matches

Revision ID: 3e12dd34ec5e
Revises: ee7215cb6fbd
Create Date: 2026-01-31 16:10:58.223281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e12dd34ec5e'
down_revision: Union[str, Sequence[str], None] = 'ee7215cb6fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('duration', sa.BigInteger(), nullable=True))
    op.add_column('matches', sa.Column('DireTeamName', sa.Text(), nullable=True))
    op.add_column('matches', sa.Column('DireTeamId', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('DireLogoTeamId', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('RadiantTeamName', sa.Text(), nullable=True))
    op.add_column('matches', sa.Column('RadiantTeamId', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('RadiantLogoTeamId', sa.String(), nullable=True))
    op.add_column('matches', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('matches', 'match_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('match_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('matches', 'status')
    op.drop_column('matches', 'RadiantLogoTeamId')
    op.drop_column('matches', 'RadiantTeamId')
    op.drop_column('matches', 'RadiantTeamName')
    op.drop_column('matches', 'DireLogoTeamId')
    op.drop_column('matches', 'DireTeamId')
    op.drop_column('matches', 'DireTeamName')
    op.drop_column('matches', 'duration')
    # ### end Alembic commands ###
