"""rename column to predict

Revision ID: 48f06f149bbd
Revises: cec2de0b4700
Create Date: 2026-03-10 14:36:34.673997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f06f149bbd'
down_revision: Union[str, Sequence[str], None] = 'cec2de0b4700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_matches', sa.Column('predict', sa.Float(), nullable=True))
    op.drop_column('live_matches', 'PredictRadiant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_matches', sa.Column('PredictRadiant', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('live_matches', 'predict')
    # ### end Alembic commands ###
