"""rename column to predict

Revision ID: 5e44f85b3ec3
Revises: 48f06f149bbd
Create Date: 2026-03-10 14:40:08.053802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e44f85b3ec3'
down_revision: Union[str, Sequence[str], None] = '48f06f149bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_matches', sa.Column('PredictRadiant', sa.Float(), nullable=True))
    op.drop_column('live_matches', 'predict')
    op.add_column('snapshot_matches', sa.Column('PredictRadiant', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('snapshot_matches', 'predict')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot_matches', sa.Column('predict', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('snapshot_matches', 'PredictRadiant')
    op.add_column('live_matches', sa.Column('predict', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('live_matches', 'PredictRadiant')
    # ### end Alembic commands ###
