"""replace big int to string on LiveMatches

Revision ID: 6e38419b4f6c
Revises: 8b67cfbd03a1
Create Date: 2025-12-30 20:58:32.322338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e38419b4f6c'
down_revision: Union[str, Sequence[str], None] = '8b67cfbd03a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('live_matches', 'DireTeamId',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('live_matches', 'DireLogoTeamId',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('live_matches', 'RadiantTeamId',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('live_matches', 'RadiantLogoTeamId',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('live_matches', 'RadiantLogoTeamId',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('live_matches', 'RadiantTeamId',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('live_matches', 'DireLogoTeamId',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('live_matches', 'DireTeamId',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    # ### end Alembic commands ###
