"""create live_matches

Revision ID: 8b67cfbd03a1
Revises: 39e9308aba1c
Create Date: 2025-12-30 20:44:40.971032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b67cfbd03a1'
down_revision: Union[str, Sequence[str], None] = '39e9308aba1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.BigInteger(), nullable=True),
    sa.Column('DireTeamName', sa.Text(), nullable=True),
    sa.Column('DireTeamId', sa.BigInteger(), nullable=True),
    sa.Column('DireLogoTeamId', sa.BigInteger(), nullable=True),
    sa.Column('RadiantTeamName', sa.Text(), nullable=True),
    sa.Column('RadiantTeamId', sa.BigInteger(), nullable=True),
    sa.Column('RadiantLogoTeamId', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_matches')
    # ### end Alembic commands ###
