"""switch pridict to json

Revision ID: cec2de0b4700
Revises: 9dd95ee03b55
Create Date: 2026-03-02 09:45:50.031341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cec2de0b4700'
down_revision: Union[str, Sequence[str], None] = '9dd95ee03b55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot_matches', sa.Column('predict', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('snapshot_matches', 'predict_radiant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot_matches', sa.Column('predict_radiant', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('snapshot_matches', 'predict')
    # ### end Alembic commands ###
